id: P00C44D4C
initial_creation_type: ocr
source_metadata:
  volumes:
    960278f646714f2a9e73b8dcd33c017a:
      base_file: v060.txt
      image_group_id: I1PD95905
      title: ''
      total_pages: 1913
      volume_number: 60
